### ISSUE TITLE
在适配器里面使用删除线越界了，暂时没有看明白什么原因

### ISSUE THREAD

**Issue by HeroBarry** [FlyJingFish/FormatTextViewLib#1]
![image](https://user-images.githubusercontent.com/7805207/236398045-954c7c0c-3a23-48ff-a149-0ad99048421e.png)

![image](https://user-images.githubusercontent.com/7805207/236398149-79541bd3-d092-49aa-ac3d-f1eb6788781f.png)

**Comment by FlyJingFish** [comment]
应该已经修复Bug了，你试一下最新版本，没问题后关闭这个Issues

**Comment by HeroBarry** [comment]
![image](https://github.com/FlyJingFish/FormatTextViewLib/assets/7805207/8a40f110-dd67-45b8-a1df-fe005dbbcff3)


修复了  可以用了
谢谢
